name : upload my image to docker hub
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build --tag myapp .
      - name: Run Docker
        run: docker run -d --name app -p 3000:3000 myapp
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # - name: Install software
      #   run: sudo apt-get install -y chromium-browser
      - name : Install necessary packages
        run: pip install requests webdriver-manager selenium pytest
      - name: Run the PyTest script
        run: pytest -rA